"use client";

import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

// Define styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: "Helvetica",
    color: "#333",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingBottom: 10,
  },
  campaignName: {
    fontSize: 10,
    textTransform: "uppercase",
    color: "#4f46e5", // indigo-600 approx
    marginBottom: 4,
  },
  sessionName: {
    fontSize: 24,
    marginBottom: 4,
  },
  date: {
    fontSize: 10,
    color: "#666",
  },
  content: {
    marginTop: 20,
  },
  sectionTitle: {
    fontSize: 16,
    marginBottom: 10,
    color: "#111",
  },
  recapText: {
    lineHeight: 1.6,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#999",
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 10,
  },
});

interface PDFRecapProps {
  sessionName: string;
  campaignName?: string;
  date: string;
  playerRecap: string;
}

export const PDFRecap = ({ sessionName, campaignName, date, playerRecap }: PDFRecapProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        {campaignName && <Text style={styles.campaignName}>{campaignName}</Text>}
        <Text style={styles.sessionName}>{sessionName}</Text>
        <Text style={styles.date}>{date}</Text>
      </View>

      <View style={styles.content}>
        <Text style={styles.sectionTitle}>Session Recap</Text>
        <Text style={styles.recapText}>{playerRecap}</Text>
      </View>

      <Text style={styles.footer} fixed>
        Generated by RPG Session Recorder & Summarizer
      </Text>
    </Page>
  </Document>
);
