"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";

interface PlayerRecapViewProps {
  sessionId: string;
  initialRecap?: string | null;
}

export function PlayerRecapView({ sessionId, initialRecap }: PlayerRecapViewProps) {
  const [recap, setRecap] = useState(initialRecap);
  const [isRegenerating, setIsRegenerating] = useState(false);

  const handleRegenerate = async () => {
    setIsRegenerating(true);
    try {
      // Trigger Inngest event to regenerate recap
      // Note: In a production app, we'd use a dedicated API route that calls inngest.send()
      // For this implementation, we follow the pattern established in AISummary.tsx
      const res = await fetch("/api/inngest/events", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: "session/transcription.completed",
          data: { sessionId },
        }),
      });

      if (res.ok) {
        alert("Recap regeneration triggered! It may take a moment to update.");
      } else {
        // Fallback if /api/inngest/events doesn't exist yet
        // Attempting to use the direct inngest serve endpoint (which might fail but matches current pattern)
        const res2 = await fetch("/api/inngest", {
          method: "POST",
          body: JSON.stringify({
            name: "session/transcription.completed",
            data: { sessionId },
          }),
        });
        
        if (res2.ok) {
          alert("Recap regeneration triggered via fallback!");
        } else {
          alert("Failed to trigger regeneration. Please ensure the Inngest event route is configured.");
        }
      }
    } catch (error) {
      console.error("Error regenerating recap:", error);
      alert("Error regenerating recap.");
    } finally {
      setIsRegenerating(false);
    }
  };

  return (
    <div className="bg-white p-6 rounded-lg shadow-md mb-6 border-t-4 border-indigo-500">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-bold text-indigo-900">Player Recap</h2>
        <div className="flex gap-2">
          <button
            onClick={handleRegenerate}
            disabled={isRegenerating}
            className="text-sm bg-indigo-100 text-indigo-700 px-3 py-1 rounded hover:bg-indigo-200 disabled:bg-gray-100 disabled:text-gray-400"
          >
            {isRegenerating ? "Regenerating..." : "Regenerate Recap"}
          </button>
        </div>
      </div>
      
      {!recap ? (
        <div className="text-gray-600 italic">
          No player recap available yet. This recap is filtered to be spoiler-free.
        </div>
      ) : (
        <div className="prose max-w-none prose-indigo">
          <ReactMarkdown>{recap}</ReactMarkdown>
        </div>
      )}
      
      <div className="mt-4 pt-4 border-t border-gray-100 text-xs text-gray-500">
        This summary is generated by AI and filtered based on your GM notes to be safe for players.
      </div>
    </div>
  );
}
